server:
  port: 8080

spring:
  application:
    name: xypai-gateway
  
  data:
    redis:
      host: localhost
      port: 6379
      password:
  
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: xypai
        group: DEFAULT_GROUP
    
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
      
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
      
      routes:
        - id: security-oauth
          uri: lb://security-oauth
          predicates:
            - Path=/auth/**
          filters:
            - CacheRequestBody
            - ValidateCodeFilter
            - StripPrefix=1

        - id: security-web
          uri: lb://security-web
          predicates:
            - Path=/admin/**
          filters:
            - CacheRequestBody
            - ValidateCodeFilter
            - StripPrefix=1

        - id: security-oauth-app
          uri: lb://security-oauth
          predicates:
            - Path=/app/**
          filters:
            - StripPrefix=1

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
          filters:
            - StripPrefix=1

        - id: xypai-gen
          uri: lb://xypai-gen
          predicates:
            - Path=/code/**
          filters:
            - StripPrefix=1

        - id: xypai-job
          uri: lb://xypai-job
          predicates:
            - Path=/schedule/**
          filters:
            - StripPrefix=1

        - id: xypai-system
          uri: lb://xypai-system
          predicates:
            - Path=/system/**
          filters:
            - StripPrefix=1

        - id: xypai-file
          uri: lb://xypai-file
          predicates:
            - Path=/file/**
          filters:
            - StripPrefix=1

        - id: social-service
          uri: lb://xypai-social
          predicates:
            - Path=/social/**
          filters:
            - StripPrefix=0
            - AddRequestHeader=X-Service-Name, social-service

        - id: wallet-service
          uri: lb://xypai-wallet
          predicates:
            - Path=/wallets/**
          filters:
            - StripPrefix=0
            - AddRequestHeader=X-Service-Name, wallet-service

        - id: feed-service
          uri: lb://xypai-feed
          predicates:
            - Path=/feeds/**
          filters:
            - StripPrefix=0
            - AddRequestHeader=X-Service-Name, feed-service

        - id: activity-service
          uri: lb://xypai-activity
          predicates:
            - Path=/activities/**
          filters:
            - StripPrefix=0
            - AddRequestHeader=X-Service-Name, activity-service

        - id: interaction-service
          uri: lb://xypai-interaction
          predicates:
            - Path=/interactions/**
          filters:
            - StripPrefix=0
            - AddRequestHeader=X-Service-Name, interaction-service

security:
  captcha:
    enabled: true
    type: math
  xss:
    enabled: true
    excludeUrls:
      - /system/notice

  ignore:
    whites:
      - /auth/login
      - /auth/logout
      - /auth/refresh
      - /auth/verify
      - /auth/user-info
      - /auth/health
      - /admin/auth/login
      - /admin/auth/logout
      - /admin/auth/refresh
      - /auth/login/sms
      - /auth/sms/send
      - /auth/info
      - /auth/validate
      - /*/v2/api-docs
      - /*/v3/api-docs
      - /actuator/**
      - /csrf
      - /auth/doc.html
      - /auth/doc.html/**
      - /auth/swagger-ui/**
      - /auth/swagger-ui.html
      - /auth/swagger-resources/**
      - /auth/v2/api-docs
      - /auth/v3/api-docs/**
        - /auth/webjars/**
        - /auth/favicon.ico
        
        # 用户服务文档接口
        - /users/health
        - /users/doc.html
        - /users/doc.html/**
        - /users/swagger-ui/**
        - /users/swagger-ui.html
        - /users/v3/api-docs/**
        - /users/webjars/**
        - /users/favicon.ico

springdoc:
  webjars:
    prefix: /webjars

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.xypai: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level [%logger{36}] - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
