server:
  port: 8080

spring:
  application:
    name: xypai-gateway
  
  data:
    redis:
      host: localhost
      port: 6379
      password:
  
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: xypai
        group: DEFAULT_GROUP
    
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
      
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
      
      routes:
        # 认证中心
        - id: xypai-auth
          uri: lb://xypai-auth
          predicates:
            - Path=/auth/**
          filters:
            # 验证码处理
            - CacheRequestBody
            - ValidateCodeFilter
            - StripPrefix=1

        # 用户模块
        - id: xypai-user
          uri: lb://xypai-user
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1

        # 内容模块
        - id: xypai-content
          uri: lb://xypai-content
          predicates:
            - Path=/content/**
          filters:
            - StripPrefix=1

        # 交易模块
        - id: xypai-trade
          uri: lb://xypai-trade
          predicates:
            - Path=/trade/**
          filters:
            - StripPrefix=1

        # 聊天模块
        - id: xypai-chat
          uri: lb://xypai-chat
          predicates:
            - Path=/chat/**
          filters:
            - StripPrefix=1

        # 代码生成
        - id: xypai-gen
          uri: lb://xypai-gen
          predicates:
            - Path=/code/**
          filters:
            - StripPrefix=1

        # 定时任务
        - id: xypai-job
          uri: lb://xypai-job
          predicates:
            - Path=/schedule/**
          filters:
            - StripPrefix=1

        # 系统模块
        - id: xypai-system
          uri: lb://xypai-system
          predicates:
            - Path=/system/**
          filters:
            - StripPrefix=1

        # 文件服务
        - id: xypai-file
          uri: lb://xypai-file
          predicates:
            - Path=/file/**
          filters:
            - StripPrefix=1

# 安全配置
security:
  # 验证码
  captcha:
    enabled: true
    type: math
  # 防止XSS攻击
  xss:
    enabled: true
    excludeUrls:
      - /system/notice

  # 不校验白名单
  ignore:
    whites:
      # 认证相关接口
      - /auth/login
      - /auth/logout
      - /auth/refresh
      - /auth/verify
      - /auth/register
      - /auth/sms/send
      - /auth/sms/verify
      - /auth/health
      
      # API文档相关
      - /*/v2/api-docs
      - /*/v3/api-docs
      - /*/v3/api-docs/**
      - /*/doc.html
      - /*/doc.html/**
      - /*/swagger-ui/**
      - /*/swagger-ui.html
      - /*/swagger-resources/**
      - /*/webjars/**
      - /*/favicon.ico
      
      # 健康检查
      - /actuator/**
      - /*/actuator/**
      
      # 其他
      - /csrf

# springdoc配置
springdoc:
  webjars:
    # 访问前缀
    prefix: /webjars

# 日志配置
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.xypai: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level [%logger{36}] - %msg%n"

# 监控配置
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
