# 共享配置文件
# Data ID: application-dev.yml
# Group: DEFAULT_GROUP

# 通用配置
server:
  # 服务器配置
  servlet:
    context-path: /
  # 错误页面配置
  error:
    whitelabel:
      enabled: false

# Spring通用配置
spring:
  # Jackson配置
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null
  
  # 上传文件配置
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

# 安全配置
security:
  # 配置不需要认证的路径
  ignore:
    whites:
      - /actuator/**
      - /swagger-ui/**
      - /v3/api-docs/**
      - /doc.html
      - /webjars/**
      - /favicon.ico
      - /error

# 全局日志配置
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: info
    org.springframework: warn
    org.apache.ibatis: warn
