# XyPai Auth App Service 最小化配置
# Data ID: xypai-auth-app-auth-dev.yml  
# Group: DEFAULT_GROUP
# 基于现有用户服务配置，只添加认证服务必需功能

# Spring配置（复用用户服务配置）
spring:
  # Redis配置 - 认证服务使用独立数据库
  data:
    redis:
      host: localhost
      port: 6379
      password:
      database: 1  # 与用户服务隔离

  # 数据源配置（完全复用用户服务配置）
  datasource:
    druid:
      stat-view-servlet:
        enabled: true
        loginUsername: ruoyi
        loginPassword: 123456
    dynamic:
      druid:
        initial-size: 5
        min-idle: 5
        maxActive: 20
        maxWait: 60000
        connectTimeout: 30000
        socketTimeout: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        filters: stat,slf4j
        connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      datasource:
        # 主库数据源（与用户服务共享）
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/ry-cloud?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
          username: root
          password: password

# MyBatis配置（调整包路径）
mybatis:
  typeAliasesPackage: com.xypai.auth.app.auth
  mapperLocations: classpath:mapper/**/*.xml

# MyBatis Plus配置（复用用户服务配置）
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      insert-strategy: not_null
      update-strategy: not_null

# SpringDoc配置（调整为认证服务）
springdoc:
  gatewayUrl: http://localhost:8080/${spring.application.name}
  api-docs:
    enabled: true
  info:
    title: 'APP认证服务接口文档'
    description: 'APP用户认证与授权服务'
    contact:
      name: XyPai Team
      url: http://www.xypai.vip
      email: admin@xypai.vip

# Knife4j配置（调整服务名称）
knife4j:
  enable: true
  setting:
    language: zh_cn
    enable-search: true
    enable-debug: true
    enable-version: true
    enable-host-text: APP认证服务
  basic:
    enable: false
    username: admin
    password: admin123

# 日志配置（调整包路径）
logging:
  level:
    com.xypai.auth.app.auth: debug
    org.springframework.cloud: warn
    org.springframework.web: info
    org.springframework.security: warn
    org.springframework.boot.autoconfigure: warn
    com.alibaba.druid: info
    root: info

# 监控端点配置（复用）
management:
  endpoints:
    web:
      exposure:
        include: 'health,info,metrics,prometheus'
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}

# 认证服务专有配置（最小必需）
auth:
  token:
    # 令牌过期时间（秒）
    expire-time: 7200
    # 刷新令牌过期时间（秒）
    refresh-expire-time: 604800
  sms:
    # 短信验证码过期时间（秒）
    code-expire-time: 300
    # 短信发送频率限制（秒）
    send-interval: 60
