# XyPai User Service 简化配置
# Data ID: xypai-user-dev.yml
# Group: DEFAULT_GROUP

# 简化数据源配置（单数据源）
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ry-cloud?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 初始连接数
      initial-size: 10
      # 最小连接池数量
      min-idle: 10
      # 最大连接池数量
      max-active: 200
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      # 配置检测连接是否有效
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false

# MyBatis Plus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0

# 日志配置
logging:
  level:
    com.xypai.user: debug
    org.springframework.cloud: warn
    root: info

# 监控端点配置
management:
  endpoints:
    web:
      exposure:
        include: 'health,info,metrics'
  endpoint:
    health:
      show-details: always

# Swagger配置
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
  info:
    title: XyPai User Service API
    description: 相遇派用户中心服务接口文档
    version: 3.6.6
